version: '3.8'

services:
  auth:
    container_name: studio-api-auth
    build:
      context: .
      target: api-auth
    ports:
      - 3000:3000

  profiles:
    container_name: studio-api-profiles
    build:
      context: .
      target: api-profiles
    ports:
      - 3001:3001

  courses:
    container_name: studio-api-courses
    build:
      context: .
      target: api-courses
    ports:
      - 3002:3002
