version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes: 
      - .volumes/mongo/data:/data/db

  auth:
    container_name: auth-dev
    depends_on: [mongo]
    build:
      context: .
      target: auth-dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

  courses:
    container_name: courses-dev
    depends_on: [mongo]
    build:
      context: .
      target: courses-dev
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app

  web:
    container_name: web-dev
    depends_on: [auth, courses]
    build:
      context: .
      target: web-dev
    ports:
      - 80:3000
    volumes:
      - .:/usr/src/app

  desing-system:
    container_name: desing-system-dev
    build:
      context: .
      target: desing-system-dev
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app

