import Head from 'next/head'
import { Fragment } from 'react'
import { SignInForm } from '../components/forms/signin'
import { Logobar } from '../components/home/LogoBar'
export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Logobar/>
        <div>
          <section id="bubbles & particles"/>
          <section id="wrapper for signin form">
            <SignInForm/>
          </section>
        </div>
      </main>

    </Fragment>
  )
}
