name: Build
on: [push, pull_request]
jobs:
  install:
    name: "Install dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Update Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn plugin import workspace-tools
          yarn --version
      - name: Install & Make dependencies for /packages first
        run: |
          yarn workspaces focus @studio/api-utils
          yarn m:dep:apiutils
      - name: Install all dependencies
        run: yarn install
  build:
    name: "Build monorepo"
    runs-on: ubuntu-latest
    needs: ["install"]
    steps: 
      - uses: actions/checkout@v3
      - name: Build Auth
        run: yarn build:api:auth
