name: "Pull Request Auto QA"
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: label-the-PR
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - id: run-frontend-tests
        if: contains(steps.label-the-PR.outputs.all-labels, 'Courses')
        run: |
          echo "Running frontend tests..."

      - id: run-backend-tests
        if: contains(steps.label-the-PR.outputs.all-labels, 'backend')
        run: |
          echo "Running backend tests..."
          # Put your commands for running backend tests here
