name: Quality Assurance
on: [pull_request]

jobs:
  AuthQA:
    if: contains( github.event.pull_request.labels.*.name, 'Auth')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Update Yarn
        run: |
          corepack enable
          corepack prepare yarn@3.3.0 --activate

      - name: Install & Make dependencies
        run: |
          yarn install
          yarn turbo run build --filter="@studio/auth"

      - name: Build auth
        run: yarn b:auth

      - name: Check linter auth
        run: yarn lint:auth

  CoursesQA:
    if: contains( github.event.pull_request.labels.*.name, 'Courses')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Update Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install & Make dependencies
        run: |
          yarn install
          yarn turbo run build --filter="@studio/courses"

      - name: Build courses
        run: yarn b:courses

      - name: Check linter courses
        run: yarn lint:courses

      - name: Check courses tests
        run: yarn test:courses

  WebQA:
    if: contains( github.event.pull_request.labels.*.name, 'Web')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Update Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install & Make dependencies
        run: |
          yarn install
          yarn turbo run build --filter="@studio/web"

      - name: Build web
        run: yarn b:web

      - name: Check linter web
        run: yarn lint:web

  DesingSystemQA:
    if: contains( github.event.pull_request.labels.*.name, 'Desing-System')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Update Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install & Make dependencies
        run: |
          yarn install
          yarn turbo run build --filter="@studio/desing-system"

      - name: Build Design System
        run: yarn b:ds

      - name: Check linter Design System
        run: yarn lint:ds
