name: Quality Assurance
on:
  push:
    branches:
      - "master"

jobs:
  QAMaster:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Update Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: yarn install

      - name: Build auth
        run: |
          yarn turbo run build --filter="@studio/auth"
          yarn b:auth
      - name: Check linter auth
        run: yarn lint:auth

      - name: Build courses
        run: |
          yarn turbo run build --filter="@studio/courses"
          yarn b:courses
      - name: Check linter courses
        run: yarn lint:courses
      - name: Check courses tests
        run: yarn test:courses

      - name: Build web
        run: |
          yarn turbo run build --filter="@studio/web"
          yarn b:web
      - name: Check linter web
        run: yarn lint:web

      - name: Build desing-system
        run: |
          yarn turbo run build --filter="@studio/desing-system"
          yarn b:ds
      - name: Check linter desing-system
        run: yarn lint:ds
