name: Quality Assurance
on:
  push:
    branches:
      - "master"

jobs:
  QAMaster:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Update Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn plugin import workspace-tools
          yarn --version
      - name: Install & Make dependencies
        run: |
          yarn workspaces focus @studio/api-utils
          yarn m:dep:apiutils
          yarn install

      - name: Build auth
        run: yarn build:api:auth
      - name: Check linter auth
        run: yarn lint:api:auth

      - name: Build courses
        run: yarn build:api:courses
      - name: Check linter courses
        run: yarn lint:api:courses

      - name: Build profiles
        run: yarn build:api:profiles
      - name: Check linter profiles
        run: yarn lint:api:profiles

      - name: Build web
        run: yarn build:app:web
      - name: Check linter web
        run: yarn lint:app:web

      - name: Build storybook
        run: yarn build:app:sb
      - name: Check linter storybook
        run: yarn lint:app:sb
